version: '2'

services:
  scoring:
    image: itsb/sc2:phase1
    working_dir: /phase1-hurdles/hurdle1
    command: bash -c "./hurdle_1.py --host=0.0.0.0 && ./calc_ber.py --truth-name=truth.bin --decoded-name=rx_packets.bin"
    volumes:
    - .:/phase1-hurdles/hurdle1
    networks:
      net:
        ipv4_address: 172.16.251.10

  solution:
    image: itsb/sc2:phase1
    working_dir: /phase1-hurdles/hurdle1
    command: bash -c "sleep 10 && ./hurdle_1_solution_stub.py --host=172.16.251.10"
    volumes:
    - .:/phase1-hurdles/hurdle1
    networks:
      net:
        ipv4_address: 172.16.251.11

networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.251.0/24
        gateway: 172.16.251.1
